run_name: OLMo-1B-sample-cpt
seed: 6198
epoch: 0
dry_run: false

model:
  d_model: 2048
  n_heads: 16
  n_layers: 16
  mlp_ratio: 8
  mlp_hidden_size: null
  activation_type: swiglu
  block_type: sequential
  block_group_size: 1
  alibi: false
  alibi_bias_max: 8.0
  rope: true
  rope_full_precision: true
  flash_attention: false
  attention_dropout: 0.0
  multi_query_attention: false
  attention_layer_norm: false
  residual_dropout: 0.0
  embedding_dropout: 0.0
  layer_norm_type: default
  layer_norm_with_affine: false
  attention_layer_norm_with_affine: false
  max_sequence_length: 2048
  include_bias: false
  bias_for_layer_norm: false
  scale_logits: false
  vocab_size: 50280
  embedding_size: 50304
  weight_tying: true
  eos_token_id: 0
  pad_token_id: 1
  init_device: meta
  init_fn: mitchell
  init_std: 0.02
  init_cutoff_factor: null
  precision: amp_bf16

optimizer:
  name: adamw
  learning_rate: 0.0004
  weight_decay: 0.1
  betas:
  - 0.9
  - 0.95
  no_decay_norm_and_bias: null
  decay_norm_and_bias: false
  decay_embeddings: false
  metrics_log_interval: 10
scheduler:
  name: cosine_with_warmup
  t_warmup: 1
  t_max: null
  alpha_f: 0.1
  grad_clip_warmup_steps: null
  grad_clip_warmup_factor: null

filter_strategy: cat_mds

data:
  paths:
  - /home1/09636/zyliu/scratch/processed_data/sample_dump_package/dedup/${filter_strategy}/train/part-000-00000.npy
  datasets: null
  pad_direction: right
  num_workers: 0
  drop_last: false
  pin_memory: true
  prefetch_factor: 16
  persistent_workers: true
  timeout: 0
restore_dataloader: true
fast_forward_batches: null
evaluators:
- label: astro-small-ppl-validation
  data:
    num_workers: 0
    drop_last: false
    datasets:
      astro-small-ppl-validation:
        - /home1/09636/zyliu/scratch/processed_data/sample_dump_package/dedup/${filter_strategy}/valid/part-0-00000.npy

eval_interval: 2
tokenizer:
  identifier: tokenizers/allenai_eleuther-ai-gpt-neox-20b-pii-special.json
  truncate_direction: right
save_folder: ""
remote_save_folder: null
canceled_check_interval: 50
save_interval: 1000
save_interval_unsharded: 10000
save_interval_ephemeral: null
save_num_checkpoints_to_keep: 9
save_num_unsharded_checkpoints_to_keep: -1
save_overwrite: false
force_save_unsharded: false
no_pre_train_checkpoint: true
load_path: 
load_path_sharded_checkpointer: null
reset_optimizer_state: false
sharded_checkpointer: torch_legacy
new_style_checkpoints: null
max_duration: 3ep # Use `ep` for #epoch, `T` for #tokens
global_train_batch_size: 2048
device_train_batch_size: 8
device_train_microbatch_size: 8
device_eval_batch_size: 8
eval_subset_num_batches: -1
eval_on_load: false
device_train_grad_accum: 1
max_grad_norm: 1.0
max_grad_norm_ratio: null
precision: amp_bf16
wandb:
  project: astro-olmo-small
  entity: astro-llm
  group: astro-olmo-small-sample
  name: astro-olmo-small-sample
  tags:
  - watching
  log_artifacts: false
  rank_zero_only: true
  log_interval: 1
speed_monitor:
  window_size: 20
  gpu_flops_available: null
console_log_interval: 1
compile: null
fsdp:
  use_orig_params: true
  sharding_strategy: FULL_SHARD
  wrapping_strategy: null
  precision: mixed
softmax_auxiliary_loss: false
time_limit: 171000.0
extra_steps_after_cancel: 10
early_stopping_factor: null
save_data_indices: true
python_profiling: false
torch_profiling: false
stop_at: null
activation_checkpointing: null
